### ISSUE TITLE
Following Usage Instructions in Rails 4 Throws "Couldn't find file 'knockout'" Error

### ISSUE THREAD

**Issue by reconstructions** [jswanner/knockoutjs-rails#7]
If I exactly follow the usage instructions in the documentation, the following error is thrown:

couldn't find file 'knockout'
  (in .../application.js:15)

If I download the knockout-3.0.0 script from the Knockout site, put it in my /app/assets/javascripts folder, and change the line in my application.js file to:
//= require knockout-3.0.0

Then everything works.  Are the instructions out of date or am I missing something here?

**Comment by michaelhawkins** [comment]
I had the same problem with knockout not found. bundle install and restarting rails server fixed it for me.

**Comment by jswanner** [comment]
Thanks @michaelhawkins for the confirmation.

Since this issue is 2 years old now, I'm going to assume it no longer needs to be open.

If someone else in the future has this problem, make sure you've installed all of your app's gems with `bundle install`, and make sure you've restarted your application server (how that's done will depend on what application server you are using).

If you continue to have a problem, you can start the Rails console, and look at the paths that your application searches for assets by running the following:

```ruby
puts Rails.application.assets.paths.sort
```

You can also check that the `knockout` JavaScript file is available to be used in a `= require` statement by ensuring it appears in the following list:

```ruby
puts Rails.application.assets.each_logical_path.to_a.sort
```
